import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import {applyCurrentSchema} from './helpers/schema.mjs';
import worker from '../src/worker.js';

test('Android 11 cashier creates a product and customer, opens hardware settings and stays responsive',async()=>{
 const db=new DatabaseSync(':memory:');applyCurrentSchema(db,{legacyMenu:true});
 const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}}},_run(){return db.prepare(sql).run(...args)}}},async batch(queries){db.exec('BEGIN');try{const result=queries.map(query=>query._run());db.exec('COMMIT');return result}catch(error){db.exec('ROLLBACK');throw error}}};
 const env={DB,ORDERING_ENABLED:'true',SESSION_SECRET:'android-counter-test-secret-1234567890123456',POS_STAFF_PASSWORD:'counter-test-password'};
 const app={innerHTML:'',querySelector:()=>null},connection={textContent:'',classList:{toggle(){}}},listeners={},intervals=new Map(),local=new Map(),session=new Map(),calls={settings:0,drafts:[],paidJobs:[],paidRecords:[]};
 const document={body:{dataset:{mode:'counter'}},hidden:false,querySelector:selector=>selector==='#app'?app:selector==='#connection'?connection:null,querySelectorAll:()=>[],addEventListener:(type,handler)=>listeners[type]=handler};
 class FakeFormData{constructor(form){this.values=form.values||{}}*entries(){yield* Object.entries(this.values)}}
 const context={document,localStorage:{getItem:key=>local.get(key)||null,setItem:(key,value)=>local.set(key,value),removeItem:key=>local.delete(key)},sessionStorage:{getItem:key=>session.get(key)||null,setItem:(key,value)=>session.set(key,value),removeItem:key=>session.delete(key)},location:{origin:'https://counter.test'},navigator:{},crypto,Response,Request,URL,FormData:FakeFormData,Intl,JSON,Number,Array,String,Math,Date,console,AbortController,AbortSignal:{},setTimeout:(fn,ms)=>ms===7000?0:setTimeout(fn,ms),clearTimeout,setInterval:(fn,ms)=>{intervals.set(ms,fn);return ms},confirm:()=>true,prompt:(_,value)=>value??'',fetch:(path,options={})=>worker.fetch(new Request('https://counter.test'+path,{method:options.method||'GET',headers:{Origin:'https://counter.test',...options.headers},body:options.body}),env)};
 context.window=context;
 context.LotusNative={displayDraft:(draft)=>calls.drafts.push(draft),displaySession(){},displayOrder(){},paymentRecorded:(order)=>calls.paidRecords.push(order),syncPaidJob:(order,job)=>calls.paidJobs.push({order,job}),getDisplays:()=> '[]',openSettings:()=>{calls.settings++},printQueue:()=> '[]'};
 vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/staff/staff.js',import.meta.url),'utf8'),context);
 assert.ok(local.get('lotus-cloud:android-paid-since'),'Save the first Android launch time before any server connection');
 assert.ok(intervals.has(3000),'Android counter checks paid remote jobs every 3 seconds');
 const click=async dataset=>listeners.click({target:{closest:()=>({dataset,disabled:false})}});
 const submit=async(id,values,editingId='')=>{
  const form={id,dataset:{id:editingId},values,classList:{contains:()=>false},elements:{namedItem:key=>{const value=values[key];return typeof value==='boolean'?{checked:value}:{value:String(value??'')}}}};
  await listeners.submit({target:form,preventDefault(){}});
 };
 await new Promise(resolve=>setTimeout(resolve,10));
 await listeners.submit({target:{id:'login',password:{value:env.POS_STAFF_PASSWORD},username:{value:'huang'}},preventDefault(){}});
 assert.match(app.innerHTML,/Giỏ món/);
 await click({screen:'products'});
 assert.ok(app.innerHTML.indexOf('id="product-form"')<app.innerHTML.indexOf('class="poc-table"'),'Android editor must be above the long product table');
 await click({action:'product-new'});
 await submit('product-form',{id:'ANDROID11',sku:'ANDROID11',name:'Món thử Android',nameCn:'安卓测试',category:'Đồ uống',station:'BAR',price:'18000',largePrice:'22000',icon:'🥤',size:true,spicy:false,active:true,recipe:''});
 assert.equal(db.prepare('SELECT price FROM pos_products WHERE id=?').get('ANDROID11').price,18000);
 await click({screen:'customers'});assert.match(app.innerHTML,/data-action="customer-new"/);
 await click({action:'customer-new'});
 const customerValues={name:'Khách thử Android',phone:'0912345678',email:'android@example.com',birthday:'',tierOverride:'AUTO',note:''};
 const customerForm={id:'customer-form',dataset:{},values:customerValues,classList:{contains:()=>false}};
 await Promise.all([listeners.submit({target:customerForm,preventDefault(){}}),listeners.submit({target:customerForm,preventDefault(){}})]);
 assert.equal(db.prepare('SELECT display_name FROM members WHERE phone=?').get('0912345678').display_name,'Khách thử Android');
 assert.equal(db.prepare('SELECT COUNT(*) AS count FROM members WHERE phone=?').get('0912345678').count,1);
 await click({screen:'settings'});assert.match(app.innerHTML,/Mở cài đặt phần cứng/);
 await click({action:'android-settings'});assert.equal(calls.settings,1);
 await Promise.all(Array.from({length:24},(_,index)=>click({screen:index%2?'customers':'products'})));
 await click({screen:'customers'});
 assert.match(app.innerHTML,/Khách thử Android/);
 await click({screen:'new'});await new Promise(resolve=>setTimeout(resolve,500));
 assert.ok(calls.drafts.length>=1&&calls.drafts.length<=2,`Expected one debounced native draft, got ${calls.drafts.length}`);
 await click({add:'101'});
 assert.match(app.innerHTML,/class="counter-grid"/);
 assert.match(app.innerHTML,/class="card-sticky"/);
 assert.match(app.innerHTML,/Giỏ món \(1\)/);
 assert.match(app.innerHTML,/1 ×/,'Customer cart on the right shows the selected item');
 await click({action:'submit'});
 const localOrder=db.prepare("SELECT id,payment_status FROM qr_orders WHERE source='POS' ORDER BY created_at DESC LIMIT 1").get();
 assert.equal(localOrder?.payment_status,'UNPAID');
 await click({pay:localOrder.id,method:'CASH'});
 assert.equal(db.prepare('SELECT payment_status FROM qr_orders WHERE id=?').get(localOrder.id).payment_status,'PAID');
 assert.ok(calls.paidRecords.includes(localOrder.id),'Payment callback reaches Android print queue');
 await click({screen:'new'});
 // A second POS confirms payment while Android has the same order open.
 db.exec('UPDATE pos_product_inventory SET stock=100; UPDATE pos_ingredients SET stock=100000;');
 const token=local.get('lotus-cloud:staff-session'),auth={Authorization:'Bearer '+token};
 const remote=async(path,method='GET',body)=>{
  const response=await worker.fetch(new Request('https://counter.test'+path,{method,headers:{...auth,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),env);
  const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data;
 };
 const created=await remote('/api/staff/orders','POST',{table:'T01',items:[{productId:'101',qty:1}],idempotencyKey:'android-display-remote-pay-00001'});
 await click({screen:'orders'});await new Promise(resolve=>setTimeout(resolve,200));await click({open:created.order.id});
 await new Promise(resolve=>setTimeout(resolve,300));
 assert.equal(JSON.parse(calls.drafts.at(-1)).orderId,created.order.id);
 const paid=await remote('/api/staff/orders/'+created.order.id+'/pay','POST',{version:created.order.version,method:'CASH',received:created.order.total});
 assert.equal(paid.order.paymentStatus,'PAID');
 await intervals.get(10000)();await new Promise(resolve=>setTimeout(resolve,300));
 assert.equal(JSON.parse(calls.drafts.at(-1)).paymentStatus,'PAID','Remote payment must refresh the customer display snapshot');
 await intervals.get(3000)();
 assert.ok(calls.paidJobs.some(x=>x.order===created.order.id),'Remote payment must enqueue kitchen and label printing without a print prompt');
 await click({screen:'customers'});await new Promise(resolve=>setTimeout(resolve,200));
 await remote('/api/staff/customers','POST',{name:'Khách từ quầy khác',phone:'0912345679'});
 await intervals.get(10000)();
 assert.match(app.innerHTML,/Khách từ quầy khác/,'Customer changes from another POS must appear without reopening the screen');
 db.close();
});
