import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import {applyCurrentSchema} from './helpers/schema.mjs';
import worker from '../src/worker.js';

test('Android 11 cashier creates a product and customer, opens hardware settings and stays responsive',async()=>{
 const db=new DatabaseSync(':memory:');applyCurrentSchema(db,{legacyMenu:true});
 const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}}},_run(){return db.prepare(sql).run(...args)}}},async batch(queries){db.exec('BEGIN');try{const result=queries.map(query=>query._run());db.exec('COMMIT');return result}catch(error){db.exec('ROLLBACK');throw error}}};
 const env={DB,ORDERING_ENABLED:'true',SESSION_SECRET:'android-counter-test-secret-1234567890123456',POS_STAFF_PASSWORD:'counter-test-password'};
 const nav={scrollTop:0,scrollLeft:0},scanner={scrolled:false,focused:false,scrollIntoView(){this.scrolled=true},focus(){this.focused=true}};
 let html='';const app={get innerHTML(){return html},set innerHTML(value){html=value;nav.scrollTop=0;nav.scrollLeft=0},querySelector:s=>s==='nav'?nav:null},connection={textContent:'',classList:{toggle(){}}},listeners={},intervals=new Map(),local=new Map(),session=new Map(),calls={settings:0,drafts:[],paidJobs:[],paidRecords:[]};
 const document={body:{dataset:{mode:'counter'}},hidden:false,querySelector:selector=>selector==='#app'?app:selector==='#connection'?connection:selector==='#scan-input'?scanner:null,querySelectorAll:()=>[],addEventListener:(type,handler)=>listeners[type]=handler};
 class FakeFormData{constructor(form){this.values=form.values||{}}*entries(){yield* Object.entries(this.values)}}
 const context={document,localStorage:{getItem:key=>local.get(key)||null,setItem:(key,value)=>local.set(key,value),removeItem:key=>local.delete(key)},sessionStorage:{getItem:key=>session.get(key)||null,setItem:(key,value)=>session.set(key,value),removeItem:key=>session.delete(key)},location:{origin:'https://counter.test'},navigator:{},crypto,Response,Request,URL,FormData:FakeFormData,Intl,JSON,Number,Array,String,Math,Date,console,AbortController,AbortSignal:{},setTimeout:(fn,ms)=>ms===7000?0:setTimeout(fn,ms),clearTimeout,setInterval:(fn,ms)=>{intervals.set(ms,fn);return ms},confirm:()=>true,prompt:(_,value)=>value??'',fetch:(path,options={})=>worker.fetch(new Request('https://counter.test'+path,{method:options.method||'GET',headers:{Origin:'https://counter.test',...options.headers},body:options.body}),env)};
 context.window=context;
 context.LotusNative={displayDraft:(draft)=>calls.drafts.push(draft),displaySession(){},displayOrder(){},paymentRecorded:(order)=>calls.paidRecords.push(order),syncPaidJob:(order,job)=>calls.paidJobs.push({order,job}),getDisplays:()=> '[]',reconnectDisplay:()=>{calls.reconnect=(calls.reconnect||0)+1},openSettings:()=>{calls.settings++},printQueue:()=> '[]'};
 vm.createContext(context);vm.runInContext(readFileSync(new URL('../public/staff/staff.js',import.meta.url),'utf8'),context);
 assert.ok(local.get('lotus-cloud:android-paid-since'),'Save the first Android launch time before any server connection');
 assert.ok(intervals.has(3000),'Android counter checks paid remote jobs every 3 seconds');
 const click=async dataset=>listeners.click({target:{closest:()=>({dataset,disabled:false})}});
 const submit=async(id,values,editingId='')=>{
  const form={id,dataset:{id:editingId},values,classList:{contains:()=>false},elements:{namedItem:key=>{const value=values[key];return typeof value==='boolean'?{checked:value}:{value:String(value??'')}}}};
  await listeners.submit({target:form,preventDefault(){}});
 };
 await new Promise(resolve=>setTimeout(resolve,10));
 await listeners.submit({target:{id:'login',password:{value:env.POS_STAFF_PASSWORD},username:{value:'huang'}},preventDefault(){}});
 assert.match(app.innerHTML,/Giỏ món/);
 const salesNav=app.innerHTML.match(/<nav aria-label="Điều hướng POS">[\s\S]*?<\/nav>/)?.[0]||'';
 assert.deepEqual([...salesNav.matchAll(/data-screen="([^"]+)"/g)].map(x=>x[1]),['new','orders','storetools']);
 await click({screen:'storetools'});assert.match(app.innerHTML,/data-screen="products"/);assert.match(app.innerHTML,/data-screen="vouchers"/);
 await click({screen:'display'});assert.match(app.innerHTML,/Chưa thấy màn hình phụ/);assert.match(app.innerHTML,/Apply Changes/);
 context.LotusNative.getDisplays=()=>JSON.stringify([{id:0,name:'Primary',width:1920,height:1200,presentation:false},{id:1,name:'Display 1',width:1280,height:720,presentation:true}]);
 await click({action:'android-display-reconnect'});assert.equal(calls.reconnect,1);assert.match(app.innerHTML,/Đã nhận 1 màn hình khách/);assert.match(app.innerHTML,/1280 × 720/);
 nav.scrollLeft=520;nav.scrollTop=33;
 await click({screen:'products'});
 assert.equal(nav.scrollLeft,520,'Bottom menu keeps its horizontal position after render');
 assert.equal(nav.scrollTop,33,'Side menu keeps its vertical position after render');
 assert.ok(app.innerHTML.indexOf('id="product-form"')<app.innerHTML.indexOf('class="poc-table"'),'Android editor must be above the long product table');
 assert.match(app.innerHTML,/商品编号（创建后不可改）/);
 await click({action:'product-new'});
 await submit('product-form',{id:'ANDROID11',sku:'ANDROID11',name:'Món thử Android',nameCn:'安卓测试',category:'Đồ uống',station:'BAR',price:'18000',largePrice:'22000',icon:'🥤',size:true,spicy:false,active:true,recipe:''});
 assert.equal(db.prepare('SELECT price FROM pos_products WHERE id=?').get('ANDROID11').price,18000);
 await click({screen:'customers'});assert.match(app.innerHTML,/data-action="customer-new"/);
 await click({action:'customer-new'});
 const customerValues={name:'Khách thử Android',phone:'0912345678',email:'android@example.com',birthday:'',tierOverride:'AUTO',note:''};
 const customerForm={id:'customer-form',dataset:{},values:customerValues,classList:{contains:()=>false}};
 await Promise.all([listeners.submit({target:customerForm,preventDefault(){}}),listeners.submit({target:customerForm,preventDefault(){}})]);
 assert.equal(db.prepare('SELECT display_name FROM members WHERE phone=?').get('0912345678').display_name,'Khách thử Android');
 assert.equal(db.prepare('SELECT COUNT(*) AS count FROM members WHERE phone=?').get('0912345678').count,1);
 await click({screen:'settings'});assert.match(app.innerHTML,/Mở cài đặt phần cứng/);
 await click({action:'android-settings'});assert.equal(calls.settings,1);
 await Promise.all(Array.from({length:24},(_,index)=>click({screen:index%2?'customers':'products'})));
 await click({screen:'customers'});
 assert.match(app.innerHTML,/Khách thử Android/);
 await click({screen:'new'});await new Promise(resolve=>setTimeout(resolve,500));
 assert.ok(calls.drafts.length>=1&&calls.drafts.length<=2,`Expected one debounced native draft, got ${calls.drafts.length}`);
 await click({add:'EC_BLEND001'});
 assert.match(app.innerHTML,/role="dialog"/,'Actual Echo mango product opens the chooser');
 await click({itemSave:''});
 assert.match(app.innerHTML,/Giỏ món \(1\)/);
 await click({cartRemove:'0'});
 await click({add:'EC_BLEND001'});
 await click({action:'focus-scanner'});
 assert.ok(scanner.scrolled&&scanner.focused,'Scanner scrolls into view and focuses even after a pending chooser');
 assert.doesNotMatch(app.innerHTML,/role="dialog"/);
 for(let i=0;i<20;i++){
  await click({add:'EC_BLEND001'});
  listeners.keydown({key:'Escape',target:{id:''},preventDefault(){}});
 }
 assert.doesNotMatch(app.innerHTML,/role="dialog"/,'Repeated open/cancel does not leave a blocking draft');
 await click({add:'EC_BLEND001'});
 assert.equal(context.LotusCounterBack(),true,'Android Back dismisses the chooser');
 assert.equal(context.LotusCounterBack(),false,'Next Back can return to Android');
 await click({add:'101'});
 assert.match(app.innerHTML,/role="dialog"/,'Counter opens an in-page item chooser, not a suppressed WebView prompt');
 await click({screen:'customers'});
 assert.match(app.innerHTML,/Khách thử Android/,'Navigation can recover from a pending item chooser');
 await click({screen:'new'});
 await click({add:'101'});
 await click({itemSave:''});
 await click({itemSave:''});
 assert.match(app.innerHTML,/class="counter-grid"/);
 assert.match(app.innerHTML,/class="card-sticky"/);
 assert.match(app.innerHTML,/Giỏ món \(1\)/);
 assert.match(app.innerHTML,/1 ×/,'Customer cart on the right shows the selected item');
 await click({action:'submit'});
 const localOrder=db.prepare("SELECT id,payment_status FROM qr_orders WHERE source='POS' ORDER BY created_at DESC LIMIT 1").get();
 assert.equal(localOrder?.payment_status,'UNPAID');
 await click({pay:localOrder.id,method:'CASH'});
 assert.equal(db.prepare('SELECT payment_status FROM qr_orders WHERE id=?').get(localOrder.id).payment_status,'PAID');
 assert.ok(calls.paidRecords.includes(localOrder.id),'Payment callback reaches Android print queue');
 await click({screen:'new'});
 // A second POS confirms payment while Android has the same order open.
 db.exec('UPDATE pos_product_inventory SET stock=100; UPDATE pos_ingredients SET stock=100000;');
 const token=local.get('lotus-cloud:staff-session'),auth={Authorization:'Bearer '+token};
 const remote=async(path,method='GET',body)=>{
  const response=await worker.fetch(new Request('https://counter.test'+path,{method,headers:{...auth,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),env);
  const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data;
 };
 const created=await remote('/api/staff/orders','POST',{table:'T01',items:[{productId:'101',qty:1}],idempotencyKey:'android-display-remote-pay-00001'});
 await click({screen:'orders'});await new Promise(resolve=>setTimeout(resolve,200));await click({open:created.order.id});
 await new Promise(resolve=>setTimeout(resolve,300));
 assert.equal(JSON.parse(calls.drafts.at(-1)).orderId,created.order.id);
 const paid=await remote('/api/staff/orders/'+created.order.id+'/pay','POST',{version:created.order.version,method:'CASH',received:created.order.total});
 assert.equal(paid.order.paymentStatus,'PAID');
 await intervals.get(10000)();await new Promise(resolve=>setTimeout(resolve,300));
 assert.equal(JSON.parse(calls.drafts.at(-1)).paymentStatus,'PAID','Remote payment must refresh the customer display snapshot');
 await intervals.get(3000)();
 assert.ok(calls.paidJobs.some(x=>x.order===created.order.id),'Remote payment must enqueue kitchen and label printing without a print prompt');
 await click({screen:'customers'});await new Promise(resolve=>setTimeout(resolve,200));
 await remote('/api/staff/customers','POST',{name:'Khách từ quầy khác',phone:'0912345679'});
 await intervals.get(10000)();
 assert.match(app.innerHTML,/Khách từ quầy khác/,'Customer changes from another POS must appear without reopening the screen');
 await click({screen:'shifts'});await new Promise(resolve=>setTimeout(resolve,200));
 const workDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 await remote('/api/staff/schedules','POST',{staffId:'OWNER',workDate,startTime:'19:13',endTime:'20:17',note:'REMOTE-ROSTER-AUDIT'});
 await intervals.get(10000)();
 assert.match(app.innerHTML,/REMOTE-ROSTER-AUDIT/,'An open roster updates after another terminal assigns a shift');
 await click({screen:'vouchers'});await new Promise(resolve=>setTimeout(resolve,200));assert.match(app.innerHTML,/最高减免（0 为不限）/);assert.match(app.innerHTML,/保存优惠券|新建优惠券/);
 const onlineFetch=context.fetch;
 context.fetch=(path,options)=>path==='/api/staff/me'?Promise.resolve(new Response('<html>Bad gateway</html>',{status:502,headers:{'Content-Type':'text/html'}})):onlineFetch(path,options);
 await click({action:'refresh'});
 assert.match(app.innerHTML,/HTTP 502.*\/api\/staff\/me/,'A non-JSON response identifies the failing API without hiding the HTTP status');
 context.fetch=onlineFetch;
 await click({action:'refresh'});
 assert.doesNotMatch(app.innerHTML,/HTTP 502.*\/api\/staff\/me/,'A successful refresh clears the transient error');
 db.close();
});
