// Local-only integration harness: Cloudflare Worker handler + node:sqlite D1-compatible adapter.
import {createServer} from 'node:http';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {resolve,join,extname,sep} from 'node:path';
import worker from '../src/worker.js';
const root=resolve(new URL('../public/',import.meta.url).pathname),db=new DatabaseSync(':memory:');
for(const n of ['0001_initial.sql','0002_customer_members_vouchers.sql','0003_pos_cloud.sql','0004_loyalty_points.sql','0005_inventory_refunds_roles.sql','0006_counter_display.sql','0007_counter_management.sql','0008_store_config.sql'])db.exec(readFileSync(new URL('../migrations/'+n,import.meta.url),'utf8'));db.exec('UPDATE pos_product_inventory SET stock=100; UPDATE pos_ingredients SET stock=100000;');
if(process.env.TEST_ENABLE_VOUCHERS==='1')db.prepare('UPDATE vouchers SET active=1,listed=1').run();
const DB={prepare(sql){let args=[];return {bind(...v){args=v;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:{changes:db.prepare(sql).run(...args).changes}}},_run(){return db.prepare(sql).run(...args)}}},async batch(queries){db.exec('BEGIN');try{const out=queries.map(x=>x._run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.png':'image/png','.svg':'image/svg+xml'};
const ASSETS={fetch:async(request)=>{let path=new URL(request.url).pathname;if(path.endsWith('/'))path+='index.html';let filename=resolve(join(root,path));if(filename!==root&&!filename.startsWith(root+sep))return new Response('not found',{status:404});try{return new Response(readFileSync(filename),{headers:{'Content-Type':types[extname(filename)]||'application/octet-stream'}})}catch{return new Response('not found',{status:404})}}};
const env={DB,ASSETS,ORDERING_ENABLED:process.env.DEMO_ONLY?'false':'true',ALLOW_UNVERIFIED_MEMBER_VOUCHERS:'true',SESSION_SECRET:'local-dev-only-strong-secret-0123456789abcdef',POS_STAFF_PASSWORD:'local-staff-password-only-for-tests',BANK_BIN:'970448',BANK_ACCOUNT_NUMBER:'12345678901',BANK_ACCOUNT_NAME:'PHAT TAI LOCAL TEST'};
const port=Number(process.env.PORT||8766);
createServer(async(req,res)=>{try{const url=new URL(req.url,`http://127.0.0.1:${port}`),chunks=[];for await(const c of req)chunks.push(c);const body=chunks.length?Buffer.concat(chunks):undefined;const request=new Request(url,{method:req.method,headers:req.headers,body,duplex:'half'});const response=await worker.fetch(request,env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()))}catch(e){console.error(e);res.writeHead(500);res.end('dev server error')}}).listen(port,'127.0.0.1',()=>console.log(`Worker+D1 local QA http://127.0.0.1:${port}`));
