import catalog from '../public/catalog.json' with {type:'json'};
import {handleStaff, paymentFor, tierFor} from './staff.js';
import {catalogInventory} from './ops.js';

const VERSION='2.1.1';
const COOKIE='__Host-lotus_qr_member';
const ERR={
 METHOD_NOT_ALLOWED:['Phương thức không được hỗ trợ','不支持此请求方式'],
 ORDERING_NOT_CONFIGURED:['Cửa hàng chưa mở nhận đơn trực tuyến','店家尚未开放线上接单'],
 SERVICE_UNAVAILABLE:['Dịch vụ đang tạm gián đoạn, thử lại sau','服务暂时不可用，请稍后重试'],
 ORIGIN_REJECTED:['Nguồn yêu cầu không hợp lệ','请求来源无效'],
 BAD_JSON:['Dữ liệu không hợp lệ','数据格式无效'],BAD_CONTENT_TYPE:['Yêu cầu phải là JSON','请求必须为 JSON 格式'],
 BODY_TOO_LARGE:['Dữ liệu quá lớn','数据过大'],
 INVALID_TABLE:['Số bàn không hợp lệ','桌号无效'],INVALID_CART:['Giỏ hàng không hợp lệ','购物车无效'],
 INVALID_ITEM:['Món không hợp lệ','菜品无效'],UNAVAILABLE_PRODUCT:['Món hiện không bán','菜品暂不可订购'],
 INVALID_QUANTITY:['Số lượng không hợp lệ','数量无效'],TOO_MANY_ITEMS:['Số món vượt giới hạn','菜品数量超出上限'],
 INVALID_MODIFIERS:['Tùy chọn món không hợp lệ','菜品选项无效'],INVALID_SIZE:['Phần ăn không hợp lệ','份量无效'],
 INVALID_SPICE:['Độ cay không hợp lệ','辣度无效'],INVALID_TOTAL:['Tổng tiền không hợp lệ','订单金额无效'],
 INVALID_REQUEST_ID:['Mã yêu cầu không hợp lệ','请求编号无效'],REQUEST_ID_REUSED:['Mã yêu cầu đã dùng cho giỏ hàng khác','请求编号已用于其他购物车'],
 TOO_MANY_ORDERS:['Gửi đơn quá nhiều, thử lại sau','订单请求过于频繁，请稍后再试'],ORDER_NOT_CONFIRMED:['Chưa nhận được xác nhận. Giỏ hàng được giữ để thử lại.','尚未收到确认，购物车已保留。'],
 INVALID_ORDER_REFERENCE:['Mã đơn không hợp lệ','订单编号无效'],ORDER_NOT_FOUND:['Không tìm thấy đơn','找不到订单'],
 ORDER_ACCESS_DENIED:['Không có quyền xem đơn này','无权查看此订单'],STATUS_UNAVAILABLE:['Không tải được đơn','无法加载订单'],
 INVALID_MEMBER:['Thông tin hội viên không hợp lệ','会员资料无效'],PHONE_EXISTS:['Số điện thoại đã có tài khoản','此手机号已有账户'],
 MEMBER_LOGIN_FAILED:['Số điện thoại hoặc mật khẩu chưa đúng','手机号或密码错误'],MEMBER_REQUIRED:['Hãy đăng nhập hội viên để dùng ưu đãi này','请先登录会员以使用此优惠'],
 PHONE_NOT_VERIFIED:['Ưu đãi hội viên yêu cầu xác minh số điện thoại; hiện chưa hỗ trợ OTP','会员优惠需要验证手机号码，目前尚未接入短信验证'],
 MEMBER_UNAVAILABLE:['Chức năng hội viên chưa khả dụng','会员服务暂不可用'],TOO_MANY_ATTEMPTS:['Thao tác quá nhiều, hãy thử lại sau 15 phút','操作过于频繁，请15分钟后再试'],
 INVALID_VOUCHER:['Mã ưu đãi không hợp lệ hoặc chưa được kích hoạt','优惠码无效或尚未启用'],
 VOUCHER_MIN:['Đơn chưa đạt mức tối thiểu để dùng ưu đãi','订单未达到优惠最低金额'],
 VOUCHER_FULL:['Ưu đãi đã hết lượt hoặc đã hết hạn','优惠已用完或已过期'],
 VOUCHER_MEMBER_LIMIT:['Hội viên đã dùng hết lượt của ưu đãi này','该会员已达到此优惠的使用次数限制'],
 VOUCHER_UNAVAILABLE:['Ưu đãi vừa hết lượt hoặc không còn khả dụng; hãy kiểm tra lại giỏ','优惠已用完或不可用，请重新检查购物车'],
 OUT_OF_STOCK:['Món vừa hết hàng; tải lại thực đơn','菜品库存不足，请刷新菜单'],
 INGREDIENT_OUT_OF_STOCK:['Nguyên liệu làm món vừa hết; tải lại thực đơn','食材库存不足，请刷新菜单']
};
const te=new TextEncoder(),td=new TextDecoder();
const headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store, max-age=0','X-Content-Type-Options':'nosniff'};
const json=(obj,status=200,extra={})=>new Response(JSON.stringify(obj),{status,headers:{...headers,...extra}});
function fail(status,code){const [message,messageCn]=ERR[code]||ERR.SERVICE_UNAVAILABLE;return json({ok:false,code,message,messageCn},status)}
const clean=(v,max=160)=>typeof v==='string'?v.trim().slice(0,max):'';
const validTable=x=>/^(T(?:0?[1-9]|[1-9][0-9])|TAKEAWAY)$/i.test(x);
const validUuid=x=>typeof x==='string'&&/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(x);
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const unb64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
const sha=async x=>hex(await crypto.subtle.digest('SHA-256',te.encode(x)));
async function sign(secret,data){const key=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',key,te.encode(data)))}
function equal(a,b){if(typeof a!=='string'||typeof b!=='string')return false;let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0}
const configured=env=>Boolean(env.DB&&typeof env.SESSION_SECRET==='string'&&env.SESSION_SECRET.length>=32);
async function ready(env){if(!configured(env))return false;try{await env.DB.prepare('SELECT id,spend,orders,last_visit FROM members LIMIT 1').first();await env.DB.prepare('SELECT id,inventory_tracked FROM qr_orders LIMIT 1').first();await env.DB.prepare('SELECT token_hash,staff_id FROM pos_staff_sessions LIMIT 1').first();await env.DB.prepare('SELECT id FROM pos_kitchen_jobs LIMIT 1').first();await env.DB.prepare('SELECT order_id FROM loyalty_transactions LIMIT 1').first();await env.DB.prepare('SELECT id FROM pos_roles LIMIT 1').first();await env.DB.prepare('SELECT product_id FROM pos_product_inventory LIMIT 1').first();await env.DB.prepare('SELECT id FROM pos_refunds LIMIT 1').first();return true}catch{return false}}
const accepting=async env=>env.ORDERING_ENABLED==='true'&&await ready(env);
function originValid(req){if(req.headers.get('Sec-Fetch-Site')==='cross-site')return false;const origin=req.headers.get('Origin');if(!origin)return true;try{return new URL(origin).origin===new URL(req.url).origin}catch{return false}}
async function body(req){if(!/^application\/json\b/i.test(req.headers.get('Content-Type')||''))throw Error('BAD_CONTENT_TYPE');if(Number(req.headers.get('Content-Length')||0)>20000)throw Error('BODY_TOO_LARGE');const value=await req.text();if(te.encode(value).byteLength>20000)throw Error('BODY_TOO_LARGE');try{return JSON.parse(value||'{}')}catch{throw Error('BAD_JSON')}}
async function rate(env,req,scope,limit=8){const now=Date.now();const key=await sha(scope+':'+clean(req.headers.get('CF-Connecting-IP')||'unknown',120));await env.DB.prepare('INSERT INTO member_auth_limits(actor_hash,attempts,reset_at) VALUES(?,1,?) ON CONFLICT(actor_hash) DO UPDATE SET attempts=CASE WHEN reset_at<=? THEN 1 ELSE attempts+1 END,reset_at=CASE WHEN reset_at<=? THEN ? ELSE reset_at END').bind(key,now+900000,now,now,now+900000).run();const result=await env.DB.prepare('SELECT attempts FROM member_auth_limits WHERE actor_hash=?').bind(key).first();return result.attempts<=limit}
async function orderRate(env,req){const now=Date.now(),ip=await sha(clean(req.headers.get('CF-Connecting-IP')||'unknown',120));await env.DB.prepare('INSERT INTO qr_order_rate(ip_hash,attempts,reset_at) VALUES(?,1,?) ON CONFLICT(ip_hash) DO UPDATE SET attempts=CASE WHEN reset_at<=? THEN 1 ELSE attempts+1 END,reset_at=CASE WHEN reset_at<=? THEN ? ELSE reset_at END').bind(ip,now+60000,now,now,now+60000).run();const result=await env.DB.prepare('SELECT attempts FROM qr_order_rate WHERE ip_hash=?').bind(ip).first();return result.attempts<=60}
function phone(v){const value=String(v||'').replace(/[\s.()-]/g,'');const vn=value.startsWith('+84')?'0'+value.slice(3):value.startsWith('84')?'0'+value.slice(2):value;return /^0[0-9]{9}$/.test(vn)?vn:''}
// PBKDF2 credential storage needs Workers Paid CPU allowance: Free offers only 10ms/request.
const ITERATIONS=120000;
async function derive(password,salt,iterations=ITERATIONS){const key=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:unb64(salt),iterations,hash:'SHA-256'},key,256))}
async function memberAuth(env,req){if(!configured(env))return null;const raw=(req.headers.get('Cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(COOKIE+'='));if(!raw)return null;const value=raw.slice(COOKIE.length+1),[payload,sig,...other]=value.split('.');if(!payload||!sig||other.length||payload.length>512)return null;if(!equal(await sign(env.SESSION_SECRET,'member:'+payload),sig))return null;try{const v=JSON.parse(td.decode(unb64(payload)));if(v.role!=='MEMBER'||!validUuid(v.jti)||Date.now()>=v.exp)return null;const s=await env.DB.prepare('SELECT m.id,m.phone,m.display_name,m.points,m.spend,m.orders,m.last_visit,m.phone_verified FROM member_sessions s JOIN members m ON m.id=s.member_id WHERE s.jti=? AND s.expires_at>?').bind(v.jti,Date.now()).first();return s?{...s,jti:v.jti}:null}catch{return null}}
async function newSession(env,memberId){const jti=crypto.randomUUID(),exp=Date.now()+7*86400000;await env.DB.prepare('INSERT INTO member_sessions(jti,member_id,expires_at) VALUES(?,?,?)').bind(jti,memberId,exp).run();const payload=b64(te.encode(JSON.stringify({role:'MEMBER',jti,exp})));const signature=await sign(env.SESSION_SECRET,'member:'+payload);return `${COOKIE}=${payload}.${signature}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`}
const clearCookie=()=>`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
const publicMember=m=>m?{id:m.id,displayName:m.display_name,phone:m.phone,phoneVerified:!!m.phone_verified,points:m.points,pointsSynced:true,tier:tierFor(m.points),spend:m.spend,orders:m.orders,lastVisit:m.last_visit}:null;
async function register(env,req){if(!(await ready(env)))return fail(503,'MEMBER_UNAVAILABLE');if(!await rate(env,req,'register',5))return fail(429,'TOO_MANY_ATTEMPTS');const b=await body(req),p=phone(b.phone),name=clean(b.name,80),pw=b.password;if(!p||name.length<2||name.length>80||typeof pw!=='string'||pw.length<10||pw.length>128)return fail(400,'INVALID_MEMBER');const found=await env.DB.prepare('SELECT id FROM members WHERE phone=?').bind(p).first();if(found)return fail(409,'PHONE_EXISTS');const salt=b64(crypto.getRandomValues(new Uint8Array(16))),passwordHash=await derive(pw,salt),id=crypto.randomUUID(),now=new Date().toISOString();try{await env.DB.prepare('INSERT INTO members(id,phone,display_name,password_salt,password_hash,hash_iterations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,p,name,salt,passwordHash,ITERATIONS,now,now).run()}catch(e){if(/UNIQUE|constraint/i.test(e.message))return fail(409,'PHONE_EXISTS');throw e}const cookie=await newSession(env,id);return json({ok:true,member:publicMember({id,phone:p,display_name:name,phone_verified:0,points:0,spend:0,orders:0,last_visit:null})},201,{'Set-Cookie':cookie})}
async function login(env,req){if(!(await ready(env)))return fail(503,'MEMBER_UNAVAILABLE');if(!await rate(env,req,'login',8))return fail(429,'TOO_MANY_ATTEMPTS');const b=await body(req),p=phone(b.phone),pw=b.password;if(!p||typeof pw!=='string'||pw.length>128)return fail(401,'MEMBER_LOGIN_FAILED');const m=await env.DB.prepare('SELECT * FROM members WHERE phone=?').bind(p).first();if(!m)return fail(401,'MEMBER_LOGIN_FAILED');const hash=await derive(pw,m.password_salt,m.hash_iterations);if(!equal(hash,m.password_hash))return fail(401,'MEMBER_LOGIN_FAILED');const cookie=await newSession(env,m.id);return json({ok:true,member:publicMember(m)},200,{'Set-Cookie':cookie})}
async function logout(env,req){const who=await memberAuth(env,req);if(who)await env.DB.prepare('DELETE FROM member_sessions WHERE jti=?').bind(who.jti).run();return json({ok:true},200,{'Set-Cookie':clearCookie()})}
function calculate(input){if(!input||typeof input!=='object'||!validTable(clean(input.table,20)))throw Error('INVALID_TABLE');if(!Array.isArray(input.items)||input.items.length<1||input.items.length>30)throw Error('INVALID_CART');let subtotal=0,units=0;const items=input.items.map(row=>{if(!row||typeof row!=='object')throw Error('INVALID_ITEM');const p=catalog.products.find(x=>String(x.id)===String(row.productId)&&x.active);if(!p||!p.available)throw Error('UNAVAILABLE_PRODUCT');const qty=row.qty;if(!Number.isSafeInteger(qty)||qty<1||qty>30)throw Error('INVALID_QUANTITY');units+=qty;if(units>60)throw Error('TOO_MANY_ITEMS');const m=row.mods||{};if(!m||typeof m!=='object'||Array.isArray(m))throw Error('INVALID_MODIFIERS');const size=m.size||'中',spice=m.spice||'中';if(!['中','大'].includes(size)||(!p.size&&size!=='中'))throw Error('INVALID_SIZE');if(!['不辣','小','中','大'].includes(spice)||(!p.spicy&&spice!=='中'))throw Error('INVALID_SPICE');const price=size==='大'?p.largePrice:p.price;subtotal+=price*qty;if(!Number.isSafeInteger(subtotal)||subtotal>100000000)throw Error('INVALID_TOTAL');return {productId:p.id,sku:p.sku,name:p.name,nameCn:p.nameCn,station:p.station,qty,price,mods:{size,spice,note:clean(m.note,100)}}});return {table:clean(input.table,20).toUpperCase(),items,subtotal,note:clean(input.note,300)}}
const voucherPublic=v=>({code:v.code,titleVi:v.title_vi,titleZh:v.title_zh,kind:v.kind,value:v.value,minSpend:v.min_spend,memberOnly:!!v.member_only});
async function resolveVoucher(env,code,subtotal,member,now){const c=clean(code,32).toUpperCase();if(!c)return null;if(!/^[A-Z0-9_-]{3,32}$/.test(c))throw Error('INVALID_VOUCHER');const v=await env.DB.prepare('SELECT * FROM vouchers WHERE code=? COLLATE NOCASE').bind(c).first();if(!v||!v.active||now<v.starts_at||now>v.ends_at)throw Error('INVALID_VOUCHER');if(v.member_only&&!member)throw Error('MEMBER_REQUIRED');if(v.member_only&&!member.phone_verified&&env.ALLOW_UNVERIFIED_MEMBER_VOUCHERS!=='true')throw Error('PHONE_NOT_VERIFIED');if(subtotal<v.min_spend)throw Error('VOUCHER_MIN');if(v.max_uses>0&&v.reserved_count+v.redeemed_count>=v.max_uses)throw Error('VOUCHER_FULL');if(member&&v.per_member_limit>0){const result=await env.DB.prepare("SELECT COUNT(*) AS n FROM voucher_reservations WHERE voucher_id=? AND member_id=? AND status IN ('HELD','REDEEMED')").bind(v.id,member.id).first();if(result.n>=v.per_member_limit)throw Error('VOUCHER_MEMBER_LIMIT')}const raw=v.kind==='PERCENT'?Math.floor(subtotal*v.value/100):v.value;return {...v,discount:Math.min(subtotal,v.max_discount>0?Math.min(raw,v.max_discount):raw)}}
function voucherError(e){const key=e?.message||'';return ['INVALID_VOUCHER','MEMBER_REQUIRED','PHONE_NOT_VERIFIED','VOUCHER_MIN','VOUCHER_FULL','VOUCHER_MEMBER_LIMIT','VOUCHER_UNAVAILABLE'].includes(key)?fail(key==='MEMBER_REQUIRED'?401:key==='PHONE_NOT_VERIFIED'?403:key==='VOUCHER_MEMBER_LIMIT'?409:400,key):fail(503,'SERVICE_UNAVAILABLE')}
async function validateVoucher(env,req){if(!(await ready(env)))return fail(503,'SERVICE_UNAVAILABLE');if(!await rate(env,req,'voucher',35))return fail(429,'TOO_MANY_ATTEMPTS');const b=await body(req),value=calculate(b),member=await memberAuth(env,req);try{const v=await resolveVoucher(env,b.voucherCode,value.subtotal,member,new Date().toISOString());if(!v)return fail(400,'INVALID_VOUCHER');return json({ok:true,voucher:voucherPublic(v),subtotal:value.subtotal,discount:v.discount,total:value.subtotal-v.discount})}catch(e){return voucherError(e)}}
function hydrate(row){return {id:row.id,code:row.code,table:row.table_id,items:JSON.parse(row.items_json),subtotal:row.subtotal??row.total,discount:row.discount||0,total:row.total,note:row.note,memberName:row.member_name||null,voucherCode:row.voucher_code||null,createdAt:row.created_at,updatedAt:row.updated_at,status:row.status,paymentStatus:row.payment_status,paymentMethod:row.payment_method||null,cashReceived:row.cash_received??null,cashChange:row.cash_change??null,source:row.source||'QR',version:row.version||1,bankPayment:paymentFor(row),...(row.paid_at?{paidAt:row.paid_at}:{})}}
async function tokenFor(env,id,idem){return sign(env.SESSION_SECRET,`order:${id}:${idem}`)}
async function submit(env,req){if(!(await accepting(env)))return fail(503,'ORDERING_NOT_CONFIGURED');const b=await body(req),idem=b.idempotencyKey;if(typeof idem!=='string'||!/^[A-Za-z0-9_-]{16,100}$/.test(idem))return fail(400,'INVALID_REQUEST_ID');const value=calculate(b),member=await memberAuth(env,req),voucherCode=clean(b.voucherCode,32).toUpperCase(),fingerprint=await sha(JSON.stringify({...value,memberId:member?.id||null,voucherCode}));
 // Resolve idempotency BEFORE revalidating voucher (an accepted voucher may now be exhausted).
 async function prior(){const row=await env.DB.prepare('SELECT * FROM qr_orders WHERE idem_key=?').bind(idem).first();if(!row)return null;if(row.fingerprint!==fingerprint)return fail(409,'REQUEST_ID_REUSED');return json({ok:true,duplicate:true,order:hydrate(row),orderToken:await tokenFor(env,row.id,idem)})}
 const previous=await prior();if(previous)return previous;if(!await orderRate(env,req))return fail(429,'TOO_MANY_ORDERS');const now=new Date().toISOString();let v;try{v=await resolveVoucher(env,voucherCode,value.subtotal,member,now)}catch(e){return voucherError(e)}const id=crypto.randomUUID(),code='PT-'+now.slice(2,10).replaceAll('-','')+'-'+id.slice(0,10).toUpperCase(),token=await tokenFor(env,id,idem);try{
  await env.DB.prepare(`INSERT INTO qr_orders (id,idem_key,fingerprint,token_hash,code,table_id,items_json,subtotal,discount,total,note,member_id,member_name,voucher_id,voucher_code,status,payment_status,created_at,updated_at,bank_bin,bank_account,bank_name,inventory_tracked) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'NEW','UNPAID',?,?,?,?,?,1) ON CONFLICT(idem_key) DO NOTHING`).bind(id,idem,fingerprint,await sha(token),code,value.table,JSON.stringify(value.items),value.subtotal,v?.discount||0,value.subtotal-(v?.discount||0),value.note,member?.id||null,member?.display_name||null,v?.id||null,v?.code||null,now,now,...bankSnapshot(env)).run();const row=await env.DB.prepare('SELECT * FROM qr_orders WHERE idem_key=?').bind(idem).first();if(!row)throw Error('ORDER_MISSING');if(row.fingerprint!==fingerprint)return fail(409,'REQUEST_ID_REUSED');const duplicate=row.id!==id;return json({ok:true,duplicate,order:hydrate(row),orderToken:await tokenFor(env,row.id,idem)},duplicate?200:201);
 }catch(e){const p=await prior();if(p)return p;if(/VOUCHER_MEMBER_LIMIT/.test(e.message))return fail(409,'VOUCHER_MEMBER_LIMIT');if(/VOUCHER_UNAVAILABLE/.test(e.message))return fail(409,'VOUCHER_UNAVAILABLE');if(e.message==='INGREDIENT_OUT_OF_STOCK')return fail(409,'INGREDIENT_OUT_OF_STOCK');if(e.message==='OUT_OF_STOCK')return fail(409,'OUT_OF_STOCK');throw e}}
async function getOrder(env,req,id){if(!(await ready(env)))return fail(503,'STATUS_UNAVAILABLE');const token=req.headers.get('x-order-token');if(!validUuid(id)||!token||token.length>128)return fail(400,'INVALID_ORDER_REFERENCE');const row=await env.DB.prepare('SELECT * FROM qr_orders WHERE id=?').bind(id).first();if(!row)return fail(404,'ORDER_NOT_FOUND');if(!equal(await sha(token),row.token_hash))return fail(403,'ORDER_ACCESS_DENIED');const returned=await env.DB.prepare('SELECT COALESCE(SUM(amount),0) AS amount FROM pos_refunds WHERE order_id=?').bind(id).first();return json({ok:true,order:{...hydrate(row),refundedAmount:returned.amount}})}
async function reportTransfer(env,req,id){if(!(await ready(env)))return fail(503,'STATUS_UNAVAILABLE');const token=req.headers.get('x-order-token');if(!validUuid(id)||!token||token.length>128)return fail(400,'INVALID_ORDER_REFERENCE');const row=await env.DB.prepare('SELECT * FROM qr_orders WHERE id=?').bind(id).first();if(!row)return fail(404,'ORDER_NOT_FOUND');if(!equal(await sha(token),row.token_hash))return fail(403,'ORDER_ACCESS_DENIED');if(!paymentFor(row)||row.status==='SPLIT'||row.status==='CANCELLED')return fail(409,'ORDER_ACCESS_DENIED');if(row.payment_status==='PAID'||row.payment_status==='CUSTOMER_REPORTED')return json({ok:true,order:hydrate(row)});const time=new Date().toISOString();await env.DB.prepare("UPDATE qr_orders SET payment_status='CUSTOMER_REPORTED',version=version+1,updated_at=? WHERE id=? AND payment_status='UNPAID' AND status IN ('NEW','ACCEPTED')").bind(time,id).run();return getOrder(env,req,id)}
function bankSnapshot(env){const bin=String(env.BANK_BIN||'970448'),account=String(env.BANK_ACCOUNT_NUMBER||'').replace(/\s/g,''),name=clean(env.BANK_ACCOUNT_NAME,100);return /^\d{6}$/.test(bin)&&/^\d{6,24}$/.test(account)&&name?[bin,account,name]:[null,null,null]}
const apiRoutes={'/api/health':['GET'],'/api/catalog':['GET'],'/api/orders':['POST'],'/api/member/me':['GET'],'/api/member/loyalty':['GET'],'/api/member/register':['POST'],'/api/member/login':['POST'],'/api/member/logout':['POST'],'/api/vouchers':['GET'],'/api/vouchers/validate':['POST']};
export default {async fetch(request,env){const url=new URL(request.url),p=url.pathname,method=request.method;
 if(p==='/kitchen'||p.startsWith('/kitchen/')||p.startsWith('/assets/kitchen'))return new Response('Not found',{status:404,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
 if(p.startsWith('/api/staff/'))return handleStaff(request,env,{ready,originValid,body,rate,calculate,resolveVoucher,hydrate,sha,equal,bankSnapshot,register,login});
 if(p.startsWith('/api/')){
  const match=p.match(/^\/api\/orders\/([0-9a-z-]+)$/i),reported=p.match(/^\/api\/orders\/([0-9a-z-]+)\/reported$/i),allowed=reported?['POST']:match?['GET']:apiRoutes[p];if(!allowed)return fail(404,'ORDER_NOT_FOUND');if(!allowed.includes(method))return json({ok:false,code:'METHOD_NOT_ALLOWED',message:ERR.METHOD_NOT_ALLOWED[0],messageCn:ERR.METHOD_NOT_ALLOWED[1]},405,{'Allow':allowed.join(', ')});
  try{if(method==='POST'&&!originValid(request))return fail(403,'ORIGIN_REJECTED');if(p==='/api/health'){const dbReady=await ready(env);return json({ok:true,d1:dbReady?'ok':'unavailable',acceptingOrders:env.ORDERING_ENABLED==='true'&&dbReady,service:'lotus-pos-cloud',version:VERSION})}if(p==='/api/catalog'){const dbReady=await ready(env);return json({ok:true,catalog:dbReady?await catalogInventory(env,catalog):catalog,acceptingOrders:env.ORDERING_ENABLED==='true'&&dbReady})}if(p==='/api/member/me'){if(!(await ready(env)))return fail(503,'MEMBER_UNAVAILABLE');return json({ok:true,member:publicMember(await memberAuth(env,request))})}if(p==='/api/member/loyalty'){if(!(await ready(env)))return fail(503,'MEMBER_UNAVAILABLE');const who=await memberAuth(env,request);if(!who)return fail(401,'MEMBER_REQUIRED');const {results=[]}=await env.DB.prepare('SELECT order_code,amount,points,paid_at FROM loyalty_transactions WHERE member_id=? ORDER BY paid_at DESC LIMIT 30').bind(who.id).all();return json({ok:true,member:publicMember(who),transactions:results.map(x=>({orderCode:x.order_code,amount:x.amount,points:x.points,paidAt:x.paid_at}))})}if(p==='/api/member/register')return register(env,request);if(p==='/api/member/login')return login(env,request);if(p==='/api/member/logout')return logout(env,request);if(p==='/api/vouchers'){if(!(await ready(env)))return fail(503,'SERVICE_UNAVAILABLE');const now=new Date().toISOString();const {results=[]}=await env.DB.prepare('SELECT * FROM vouchers WHERE listed=1 AND active=1 AND starts_at<=? AND ends_at>=? AND (max_uses=0 OR reserved_count+redeemed_count<max_uses) ORDER BY code LIMIT 20').bind(now,now).all();return json({ok:true,vouchers:results.map(voucherPublic)})}if(p==='/api/vouchers/validate')return validateVoucher(env,request);if(p==='/api/orders')return submit(env,request);if(reported)return reportTransfer(env,request,reported[1]);if(match)return getOrder(env,request,match[1]);
  }catch(e){if(ERR[e.message]&&['BAD_JSON','BAD_CONTENT_TYPE','BODY_TOO_LARGE','INVALID_TABLE','INVALID_CART','INVALID_ITEM','UNAVAILABLE_PRODUCT','INVALID_QUANTITY','TOO_MANY_ITEMS','INVALID_MODIFIERS','INVALID_SIZE','INVALID_SPICE','INVALID_TOTAL'].includes(e.message))return fail(400,e.message);console.error('Customer QR API error:',e.message);return fail(503,'SERVICE_UNAVAILABLE')}
 }
 const response=await env.ASSETS.fetch(request);if(['/','/index.html','/qr/','/staff/','/staff/index.html','/manifest.webmanifest','/sw.js','/offline.html'].includes(p)){const h=new Headers(response.headers);h.set('Cache-Control','no-cache, must-revalidate');h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','same-origin');h.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}return response;
}};
